using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("OzekiDemoSoftphone")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Ozeki Ltd.")]
[assembly: AssemblyProductAttribute("OzekiDemoSoftphone")]
[assembly: AssemblyCopyrightAttribute("Copyright © Ozeki Ltd. 2012")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("4664f6ca-c021-40cd-ae8e-a3d8cb857bc2")]
[assembly: AssemblyVersionAttribute("10.1.2.500")]

